/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.netbeans.modules.docker.command.project.ui;

import java.awt.Dialog;
import org.netbeans.modules.docker.command.DockerExecutablePreference;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;

public class EditDockerExecutablePathPanel extends javax.swing.JPanel {

    private DialogDescriptor descriptor = null;

    public EditDockerExecutablePathPanel() {
        initComponents();
        init();
    }
    
    private void init() {
        dockerExecutablePath.setText(DockerExecutablePreference.getDockerExecutablePath());
    }

    public boolean open() {
        descriptor = new DialogDescriptor(
                this,
                "Edit docker executable path",
                true,
                NotifyDescriptor.OK_CANCEL_OPTION,
                NotifyDescriptor.OK_OPTION,
                null);
        Dialog dialog = DialogDisplayer.getDefault().createDialog(descriptor);

        try {
            dialog.setVisible(true);
        } finally {
            dialog.dispose();
        }

        return descriptor.getValue() == NotifyDescriptor.OK_OPTION;
    }
    
    public String getDockerExecutablePath() {
        return dockerExecutablePath.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dockerExecutableNameL = new javax.swing.JLabel();
        dockerExecutablePath = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(dockerExecutableNameL, org.openide.util.NbBundle.getMessage(EditDockerExecutablePathPanel.class, "EditDockerExecutablePathPanel.dockerExecutableNameL.text")); // NOI18N

        dockerExecutablePath.setText(org.openide.util.NbBundle.getMessage(EditDockerExecutablePathPanel.class, "EditDockerExecutablePathPanel.dockerExecutablePath.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dockerExecutableNameL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dockerExecutablePath, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dockerExecutableNameL)
                    .addComponent(dockerExecutablePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dockerExecutableNameL;
    private javax.swing.JTextField dockerExecutablePath;
    // End of variables declaration//GEN-END:variables
}
