/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.netbeans.modules.docker.execution.containers.ui;

/**
 *
 * @author bhaidu
 */
public class NewDockerContainerConfigPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewContainerPanel
     */
    public NewDockerContainerConfigPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerConfigNameL = new javax.swing.JLabel();
        containerConfigName = new javax.swing.JTextField();
        dockerContainerNameL = new javax.swing.JLabel();
        dockerContainerName = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(containerConfigNameL, org.openide.util.NbBundle.getMessage(NewDockerContainerConfigPanel.class, "NewDockerContainerConfigPanel.containerConfigNameL.text")); // NOI18N

        containerConfigName.setText(org.openide.util.NbBundle.getMessage(NewDockerContainerConfigPanel.class, "NewDockerContainerConfigPanel.containerConfigName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dockerContainerNameL, org.openide.util.NbBundle.getMessage(NewDockerContainerConfigPanel.class, "NewDockerContainerConfigPanel.dockerContainerNameL.text")); // NOI18N

        dockerContainerName.setText(org.openide.util.NbBundle.getMessage(NewDockerContainerConfigPanel.class, "NewDockerContainerConfigPanel.dockerContainerName.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerConfigNameL)
                    .addComponent(dockerContainerNameL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dockerContainerName, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(containerConfigName))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(containerConfigNameL)
                    .addComponent(containerConfigName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dockerContainerNameL)
                    .addComponent(dockerContainerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField containerConfigName;
    private javax.swing.JLabel containerConfigNameL;
    private javax.swing.JTextField dockerContainerName;
    private javax.swing.JLabel dockerContainerNameL;
    // End of variables declaration//GEN-END:variables
}
