/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.netbeans.modules.docker.execution.project.ui;

import java.io.File;
import java.util.Set;
import org.netbeans.api.project.Project;
import org.netbeans.modules.docker.execution.DockerExecModel;
import org.netbeans.modules.docker.execution.project.ConfigManager;
import org.netbeans.modules.docker.execution.project.ConfigManager.Configuration;
import org.netbeans.modules.docker.execution.project.DockerConfigManager;
import org.netbeans.modules.docker.execution.project.DockerExecConfiguration;
import static org.netbeans.modules.docker.execution.project.DockerServiceProjectProperties.*;
import org.netbeans.modules.docker.execution.project.DockerServiceProjectProperties;
import org.netbeans.modules.docker.execution.project.DockerSettings;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;
import org.openide.util.NbBundle;

public class DockerExecutableConfigPanel extends javax.swing.JPanel {

    private final Project project;
    private final DockerExecModel dockerModel;
    private final DockerServiceProjectProperties properties;
    private final DockerConfigComboBoxModel1 comboModel;
    private final DockerConfigComboBoxModel1 npmComboModel;

    public DockerExecutableConfigPanel(Project project) {
        this.properties = null;
        this.project = project;
        this.dockerModel = new DockerExecModel(project);
        initComponents();
        
        Set<String> profiles = dockerModel.getProfiles();
        comboModel = DockerConfigComboBoxModel1.build(profiles);
        npmComboModel = DockerConfigComboBoxModel1.build(profiles);
        ConfigOptionCombo.setModel(comboModel);
        nodeNpmDockerConfigCombo.setModel(npmComboModel);

        init();
    }
//
//    @Override
//    public void addNotify() {
//        super.addNotify();
//        ConfigOptionCombo.setSelectedItem(manager.currentConfiguration().getName());
//    }

    private void init() {
        //validate configProfile
        comboModel.setSelectedItem(dockerModel.getCurrentProfile());
        loadDockerExecSettings();
    }

    public void saveSettings() {
        String selectedProfile = (String) ConfigOptionCombo.getSelectedItem();
        DockerExecConfiguration config = createConfig();
        DockerConfigManager.saveConfigProfile(dockerModel, config, selectedProfile, project);
    }

    private void loadDockerExecSettings() {
        String currentProfile = (String) comboModel.getSelectedItem();
        DockerExecConfiguration config = dockerModel.getConfiguration(currentProfile);
        dockerContainerName.setText(config.getContainerName());
        dockerBashType.setText(config.getBashType());
        dockerInteractive.setSelected(config.getInteractive());
        dockerPseudoTerminal.setSelected(config.getAsTerminal());
        dockerUser.setText(config.getDockerUser());
        dockerVolumeDir.setText(config.getDockerWorkDir());
        //configDel.setEnabled(!config.isDefault());
    }
    
    private DockerExecConfiguration createConfig() {
        return new DockerExecConfiguration(
            dockerContainerName.getText(),
            dockerBashType.getText(),
            dockerInteractive.isSelected(),
            dockerPseudoTerminal.isSelected(),
            dockerUser.getText(),
            dockerVolumeDir.getText()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBL_ContainerName = new javax.swing.JLabel();
        dockerContainerName = new javax.swing.JTextField();
        LBL_BashType = new javax.swing.JLabel();
        dockerBashType = new javax.swing.JTextField();
        LBL_User = new javax.swing.JLabel();
        dockerUser = new javax.swing.JTextField();
        dockerPseudoTerminal = new javax.swing.JCheckBox();
        dockerInteractive = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        LBL_DockerWorkdir = new javax.swing.JLabel();
        dockerVolumeDir = new javax.swing.JTextField();
        LBL_Configuration = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ConfigOptionCombo = new javax.swing.JComboBox<>();
        configNew = new javax.swing.JButton();
        configDel = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        npmNodeDockerEnabled = new javax.swing.JCheckBox();
        nodeNpmDockerConfigCombo = new javax.swing.JComboBox<>();

        org.openide.awt.Mnemonics.setLocalizedText(LBL_ContainerName, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.LBL_ContainerName.text")); // NOI18N

        dockerContainerName.setText(org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.dockerContainerName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(LBL_BashType, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.LBL_BashType.text")); // NOI18N

        dockerBashType.setText(org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.dockerBashType.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(LBL_User, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.LBL_User.text")); // NOI18N

        dockerUser.setText(org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.dockerUser.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dockerPseudoTerminal, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.dockerPseudoTerminal.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dockerInteractive, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.dockerInteractive.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(LBL_DockerWorkdir, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.LBL_DockerWorkdir.text")); // NOI18N

        dockerVolumeDir.setText(org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.dockerVolumeDir.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(LBL_Configuration, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.LBL_Configuration.text")); // NOI18N

        ConfigOptionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configComboActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(configNew, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.configNew.text")); // NOI18N
        configNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configNewActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(configDel, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.configDel.text")); // NOI18N
        configDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configDelActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(npmNodeDockerEnabled, org.openide.util.NbBundle.getMessage(DockerExecutableConfigPanel.class, "DockerExecutableConfigPanel.npmNodeDockerEnabled.text")); // NOI18N

        nodeNpmDockerConfigCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodeNpmDockerConfigComboconfigComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_User)
                                .addGap(106, 106, 106)
                                .addComponent(dockerUser))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_ContainerName)
                                .addGap(28, 28, 28)
                                .addComponent(dockerContainerName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_Configuration)
                                .addGap(43, 43, 43)
                                .addComponent(ConfigOptionCombo, 0, 273, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(configNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(configDel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dockerInteractive)
                                    .addComponent(dockerPseudoTerminal)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_BashType)
                                .addGap(69, 69, 69)
                                .addComponent(dockerBashType))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_DockerWorkdir)
                                .addGap(37, 37, 37)
                                .addComponent(dockerVolumeDir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(npmNodeDockerEnabled)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nodeNpmDockerConfigCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfigOptionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(configNew)
                    .addComponent(configDel)
                    .addComponent(LBL_Configuration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dockerContainerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBL_ContainerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_BashType)
                    .addComponent(dockerBashType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dockerUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBL_User))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dockerPseudoTerminal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dockerInteractive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_DockerWorkdir)
                    .addComponent(dockerVolumeDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(npmNodeDockerEnabled)
                    .addComponent(nodeNpmDockerConfigCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configNewActionPerformed
        NotifyDescriptor.InputLine d = new NotifyDescriptor.InputLine(
                NbBundle.getMessage(DockerExecutableConfigPanel.class, "LBL_ConfigurationName"),
                NbBundle.getMessage(DockerExecutableConfigPanel.class, "LBL_CreateNewConfiguration"));

        if (DialogDisplayer.getDefault().notify(d) == NotifyDescriptor.OK_OPTION) {
            String name = d.getInputText();
            if (name.trim().length() == 0) {
                DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message(
                        NbBundle.getMessage(DockerExecutableConfigPanel.class, "MSG_ConfigurationNameBlank"),
                        NotifyDescriptor.WARNING_MESSAGE));
                return;
            }
            String configName = name.replaceAll("[^a-zA-Z0-9_.-]", "_"); // NOI18N

            if (dockerModel.profileExists(configName)) {
                DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message(
                        NbBundle.getMessage(DockerExecutableConfigPanel.class, "MSG_ConfigurationExists", configName),
                        NotifyDescriptor.WARNING_MESSAGE));
                return;
            }

            DockerExecConfiguration config = createConfig();
            DockerConfigManager.saveConfigProfile(dockerModel, config, configName, project);

            comboModel.addElement(configName);
            comboModel.setSelectedItem(configName);
            npmComboModel.addElement(configName);

            loadDockerExecSettings();
        }
    }//GEN-LAST:event_configNewActionPerformed

    private void configComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configComboActionPerformed
        loadDockerExecSettings();
    }//GEN-LAST:event_configComboActionPerformed

    private void nodeNpmDockerConfigComboconfigComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodeNpmDockerConfigComboconfigComboActionPerformed
        
    }//GEN-LAST:event_nodeNpmDockerConfigComboconfigComboActionPerformed

    private void configDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configDelActionPerformed
        String currentProfile = (String) comboModel.getSelectedItem();
        dockerModel.remove(currentProfile);
        comboModel.removeElement(currentProfile);
    }//GEN-LAST:event_configDelActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ConfigOptionCombo;
    private javax.swing.JLabel LBL_BashType;
    private javax.swing.JLabel LBL_Configuration;
    private javax.swing.JLabel LBL_ContainerName;
    private javax.swing.JLabel LBL_DockerWorkdir;
    private javax.swing.JLabel LBL_User;
    private javax.swing.JButton configDel;
    private javax.swing.JButton configNew;
    private javax.swing.JTextField dockerBashType;
    private javax.swing.JTextField dockerContainerName;
    private javax.swing.JCheckBox dockerInteractive;
    private javax.swing.JCheckBox dockerPseudoTerminal;
    private javax.swing.JTextField dockerUser;
    private javax.swing.JTextField dockerVolumeDir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> nodeNpmDockerConfigCombo;
    private javax.swing.JCheckBox npmNodeDockerEnabled;
    // End of variables declaration//GEN-END:variables
}
