/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.netbeans.modules.docker.cli.config.containers.ui;

import java.awt.Dialog;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.NbBundle;

public class NewDockerContainerConfigPanel extends javax.swing.JPanel {

    private DialogDescriptor descriptor = null;

    /**
     * Creates new form NewContainerPanel
     */
    public NewDockerContainerConfigPanel() {
        initComponents();
    }

    public boolean open() {
        descriptor = new DialogDescriptor(
                this,
                NbBundle.getMessage(NewDockerContainerConfigPanel.class,
                        "NewDockerContainerConfigPanel.title"),
                true,
                NotifyDescriptor.OK_CANCEL_OPTION,
                NotifyDescriptor.OK_OPTION,
                null);
        Dialog dialog = DialogDisplayer.getDefault().createDialog(descriptor);

        try {
            dialog.setVisible(true);
        } finally {
            dialog.dispose();
        }

        return descriptor.getValue() == NotifyDescriptor.OK_OPTION;
    }
    
    public String getDockerContainerName() {
        return dockerContainerName.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dockerContainerNameL = new javax.swing.JLabel();
        dockerContainerName = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(dockerContainerNameL, org.openide.util.NbBundle.getMessage(NewDockerContainerConfigPanel.class, "NewDockerContainerConfigPanel.dockerContainerNameL.text")); // NOI18N

        dockerContainerName.setText(org.openide.util.NbBundle.getMessage(NewDockerContainerConfigPanel.class, "NewDockerContainerConfigPanel.dockerContainerName.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dockerContainerNameL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dockerContainerName, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dockerContainerNameL)
                    .addComponent(dockerContainerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dockerContainerName;
    private javax.swing.JLabel dockerContainerNameL;
    // End of variables declaration//GEN-END:variables
}
